<?php

return [
    'invite_days' => 7,
    'invite_host' => env('REFERRAL_LINK_HOST', env('CONSULTANT_FRONTEND_URL', 'https://rcicmaster.ca')),
    'assignable' => [
        'dashboard.view',
        'clients.view',
        'clients.create',
        'clients.edit',
        'clients.notes',
        'cases.view',
        'cases.create',
        'cases.edit',
        'cases.notes',
        'cases.tasks',
        'cases.assign',
        'cases.status_update',
        'documents.view',
        'documents.request',
        'documents.upload',
        'documents.request_correction',
        'forms.view',
        'forms.prepare',
        'forms.edit',
        'assessments.view',
        'assessments.prepare',
        'pathways.view',
        'pathways.recommend',
        'application.prepare',
        'application.review',
        'submission.view',
        'calendar.view',
        'calendar.manage',
        'tasks.view',
        'tasks.create',
        'tasks.edit',
        'communications.view',
        'communications.send',
        'team.view',
        'letters.use',
        'legislations.view',
        'community.view',
        'storage.view',
        'storage.manage',
        'marketing.view',
        'lms.view',
        'academy.learn',
    ],
    'owner_only' => [
        'clients.archive',
        'cases.close',
        'documents.verify',
        'forms.review',
        'assessments.approve',
        'pathways.confirm',
        'application.signoff',
        'submission.authorize',
        'billing.view',
        'billing.manage',
        'subscription.manage',
        'referral.view',
        'wallet.view',
        'team.manage',
        'workspace.transfer',
        'retainer.send',
        'representative.manage',
        'signature.use_owner',
    ],
    'presets' => [
        'case_manager' => [
            'name' => 'Case Manager',
            'permissions' => [
                'dashboard.view', 'clients.view', 'clients.create', 'clients.edit', 'clients.notes',
                'cases.view', 'cases.create', 'cases.edit', 'cases.notes', 'cases.tasks', 'cases.assign', 'cases.status_update',
                'documents.view', 'documents.request', 'documents.upload', 'documents.request_correction',
                'forms.view', 'forms.prepare', 'forms.edit',
                'assessments.view', 'assessments.prepare',
                'pathways.view', 'pathways.recommend',
                'application.prepare', 'application.review', 'submission.view',
                'calendar.view', 'calendar.manage', 'tasks.view', 'tasks.create', 'tasks.edit',
                'communications.view', 'communications.send', 'team.view',
            ],
        ],
        'case_worker' => [
            'name' => 'Case Worker',
            'permissions' => [
                'dashboard.view', 'clients.view', 'clients.edit', 'clients.notes',
                'cases.view', 'cases.edit', 'cases.notes', 'cases.tasks',
                'documents.view', 'documents.request', 'documents.upload', 'documents.request_correction',
                'forms.view', 'forms.prepare', 'forms.edit',
                'assessments.view', 'assessments.prepare',
                'pathways.view', 'pathways.recommend',
                'application.prepare', 'submission.view',
                'calendar.view', 'tasks.view', 'tasks.create', 'tasks.edit',
                'communications.view', 'communications.send',
            ],
        ],
        'assistant' => [
            'name' => 'Assistant',
            'permissions' => [
                'dashboard.view', 'clients.view', 'clients.notes',
                'cases.view', 'cases.notes', 'cases.tasks',
                'documents.view', 'documents.upload',
                'forms.view',
                'assessments.view', 'pathways.view', 'submission.view',
                'calendar.view', 'calendar.manage', 'tasks.view', 'tasks.create',
                'communications.view', 'communications.send',
            ],
        ],
        'document_specialist' => [
            'name' => 'Document Specialist',
            'permissions' => [
                'dashboard.view', 'clients.view',
                'cases.view',
                'documents.view', 'documents.request', 'documents.upload', 'documents.request_correction',
                'forms.view', 'forms.prepare', 'forms.edit',
                'application.prepare',
            ],
        ],
        'billing_staff' => [
            'name' => 'Billing Staff',
            'permissions' => [
                'dashboard.view',
            ],
        ],
        'read_only' => [
            'name' => 'Read Only',
            'permissions' => [
                'dashboard.view', 'clients.view', 'cases.view', 'documents.view', 'forms.view',
                'assessments.view', 'pathways.view', 'submission.view', 'calendar.view', 'tasks.view',
                'communications.view', 'team.view',
            ],
        ],
    ],
];
