<?php

namespace App\Models;

use App\Enums\GovernmentFormGenerationStatus;
use App\Enums\GovernmentFormGenerationType;
use App\Enums\GovernmentFormReviewStatus;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class IrccPackageDocumentSubmission extends Model
{
    protected $connection = 'cws';

    protected $fillable = [
        'case_file_id',
        'ircc_category_document_id',
        'uploaded_by',
        'file_path',
        'original_filename',
        'mime_type',
        'file_size',
        'status',
        'submitted_at',
        'generation_type',
        'government_form_version_id',
        'mapping_version',
        'source_template_hash',
        'source_data_hash',
        'output_sha256',
        'generated_by',
        'generated_at',
        'review_status',
        'supersedes_id',
        'generation_status',
        'storage_disk',
    ];

    protected function casts(): array
    {
        return [
            'submitted_at'      => 'datetime',
            'generated_at'      => 'datetime',
            'file_size'         => 'integer',
            'generation_type'   => GovernmentFormGenerationType::class,
            'generation_status' => GovernmentFormGenerationStatus::class,
            'review_status'     => GovernmentFormReviewStatus::class,
        ];
    }

    public function caseFile(): BelongsTo
    {
        return $this->belongsTo(CaseFile::class);
    }

    public function uploader(): BelongsTo
    {
        return $this->belongsTo(User::class, 'uploaded_by');
    }

    public function generator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    public function governmentFormVersion(): BelongsTo
    {
        return $this->belongsTo(GovernmentFormVersion::class);
    }

    public function supersedes(): BelongsTo
    {
        return $this->belongsTo(self::class, 'supersedes_id');
    }

    public function isAutoGenerated(): bool
    {
        return $this->generation_type === GovernmentFormGenerationType::AUTO_GENERATED;
    }

    public function isPrivateStorage(): bool
    {
        return $this->storage_disk === 'local' || $this->isAutoGenerated();
    }
}
