<?php

namespace App\Services\CourseFactory\Pipeline;

use App\Jobs\CourseFactory\AdvanceCourseFactoryJob;
use App\Jobs\CourseFactory\PollManusCourseFactoryJob;
use App\Models\CourseFactory\CfGenerationRun;
use App\Models\CourseFactory\CfGenerationStep;
use App\Models\Lms\LmsCategory;
use App\Models\Lms\LmsCourse;
use App\Services\CourseFactory\Prompts\PromptCatalog;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CourseFactoryOrchestrator
{
    public function __construct(
        private GenerationEventWriter $events,
        private StageProcessor $stages,
    ) {}

    /**
     * @param  array<string, mixed>  $options
     */
    public function start(int $adminUserId, string $examName, array $options = []): CfGenerationRun
    {
        $examName = trim($examName);
        if ($examName === '') {
            throw new \InvalidArgumentException('Exam name is required.');
        }

        $config = array_merge(config('course_factory'), ['options' => $options]);
        // Never persist raw provider secrets into generation snapshots.
        unset($config['openai']['key'], $config['manus']['api_key']);
        $config['openai']['key_configured'] = filled(config('course_factory.openai.key') ?: config('services.openai.key'));
        $config['manus']['key_configured'] = filled(config('course_factory.manus.api_key'));

        $run = DB::connection('lms')->transaction(function () use ($adminUserId, $examName, $config) {
            $run = CfGenerationRun::query()->create([
                'admin_user_id' => $adminUserId,
                'exam_name' => $examName,
                'status' => 'running',
                'overall_progress' => 0,
                'current_step' => 'exam_discovery',
                'config_snapshot' => $config,
                'research_version' => '1',
                'generation_version' => PromptCatalog::VERSION,
                'started_at' => now(),
            ]);

            foreach (PipelineDefinition::steps() as $i => $step) {
                CfGenerationStep::query()->create([
                    'generation_run_id' => $run->id,
                    'step_key' => $step['key'],
                    'step_name' => $step['name'],
                    'sequence' => $i + 1,
                    'status' => 'pending',
                    'progress' => 0,
                ]);
            }

            $slug = Str::slug($examName).'-'.Str::lower(Str::random(6));
            $category = LmsCategory::query()->firstOrCreate(
                ['slug' => 'ai-course-factory'],
                [
                    'name' => 'AI Course Factory',
                    'description' => 'Courses generated by AI Course Factory (pending review).',
                    'sort_order' => 0,
                    'is_active' => true,
                ]
            );

            $course = LmsCourse::query()->create([
                'category_id' => $category->id,
                'title' => $examName.' — Generating…',
                'slug' => $slug,
                'description' => 'AI Course Factory draft — not published.',
                'is_published' => false,
                'review_status' => 'generating',
                'sort_order' => 0,
                'currency' => 'CAD',
                'price_cents' => null,
                'commerce_confirmed' => false,
                'access_mode' => 'self_purchase',
                'audience' => 'consultant',
                'access_months' => (int) config('learning.default_access_months', 3),
                'cf_generation_run_id' => $run->id,
            ]);

            $run->update(['course_id' => $course->id]);

            return $run->fresh(['steps']);
        });

        $this->events->write($run, 'run_started', 'Generation started', 'Exam: '.$examName, 'Orchestrator');

        AdvanceCourseFactoryJob::dispatch($run->id);

        return $run;
    }

    public function advance(int $runId): void
    {
        $run = CfGenerationRun::query()->with('steps')->findOrFail($runId);

        if (in_array($run->status, ['cancelled', 'failed', 'pending_review'], true)) {
            return;
        }

        $step = $run->steps->first(function (CfGenerationStep $s) {
            return in_array($s->status, ['pending', 'retrying', 'running', 'waiting_external'], true);
        });

        if (! $step) {
            return;
        }

        if ($step->status === 'waiting_external') {
            PollManusCourseFactoryJob::dispatch($run->id, $step->id);

            return;
        }

        try {
            $step->update([
                'status' => 'running',
                'started_at' => $step->started_at ?? now(),
                'progress' => max(5, (int) $step->progress),
            ]);
            $run->update([
                'status' => 'running',
                'current_step' => $step->step_key,
            ]);

            $result = $this->stages->run($run->fresh(), $step->fresh());

            if (($result['status'] ?? '') === 'waiting_external') {
                $step->update([
                    'status' => 'waiting_external',
                    'external_provider' => $result['external_provider'] ?? 'manus',
                    'external_task_id' => $result['external_task_id'] ?? null,
                    'metadata' => array_merge($step->metadata ?? [], $result['metadata'] ?? []),
                    'progress' => 40,
                ]);
                $this->refreshProgress($run);
                PollManusCourseFactoryJob::dispatch($run->id, $step->id);

                return;
            }

            if (($result['status'] ?? '') === 'continue') {
                $step->update([
                    'progress' => (int) ($result['progress'] ?? $step->progress),
                    'metadata' => array_merge($step->metadata ?? [], $result['metadata'] ?? []),
                    'generated_records_count' => (int) ($result['generated_records_count'] ?? $step->generated_records_count),
                ]);
                $this->refreshProgress($run);
                AdvanceCourseFactoryJob::dispatch($run->id);

                return;
            }

            $step->update([
                'status' => 'completed',
                'progress' => 100,
                'completed_at' => now(),
                'generated_records_count' => (int) ($result['generated_records_count'] ?? $step->generated_records_count),
                'metadata' => array_merge($step->metadata ?? [], $result['metadata'] ?? []),
            ]);

            $this->events->write(
                $run,
                $step->step_key.'_completed',
                $step->step_name.' completed',
                $result['message'] ?? null,
                $result['agent'] ?? 'OpenAI'
            );

            if ($step->step_key === 'admin_review') {
                $run->update([
                    'status' => 'pending_review',
                    'overall_progress' => 100,
                    'completed_at' => now(),
                    'current_step' => 'admin_review',
                ]);
                if ($run->course_id) {
                    LmsCourse::query()->where('id', $run->course_id)->update(['review_status' => 'pending_review']);
                }
                $this->events->write($run, 'course_generation_completed', 'Pending Admin Review', 'All mandatory stages passed.', 'Orchestrator');

                return;
            }

            $this->refreshProgress($run);
            AdvanceCourseFactoryJob::dispatch($run->id);
        } catch (\Throwable $e) {
            $max = (int) config('course_factory.max_retries', 3);
            $retry = (int) $step->retry_count + 1;
            $step->update([
                'retry_count' => $retry,
                'error_message' => $e->getMessage(),
                'error_code' => class_basename($e),
                'status' => $retry <= $max ? 'retrying' : 'failed',
            ]);

            $this->events->write(
                $run,
                $step->step_key.'_failed',
                $step->step_name.' failed',
                $e->getMessage(),
                'Orchestrator',
                ['retry' => $retry],
                'error'
            );

            if ($retry <= $max) {
                AdvanceCourseFactoryJob::dispatch($run->id)->delay(now()->addSeconds(min(60, 5 * $retry)));

                return;
            }

            $run->update([
                'status' => 'failed',
                'failed_at' => now(),
                'error_summary' => $e->getMessage(),
            ]);
            if ($run->course_id) {
                LmsCourse::query()->where('id', $run->course_id)->update(['review_status' => 'generation_failed']);
            }
        }
    }

    public function cancel(CfGenerationRun $run): void
    {
        if ($run->isTerminal() && $run->status !== 'generation_incomplete') {
            return;
        }

        $run->update([
            'status' => 'cancelled',
            'cancelled_at' => now(),
        ]);
        $run->steps()
            ->whereIn('status', ['pending', 'running', 'waiting_external', 'retrying'])
            ->update(['status' => 'cancelled']);

        $this->events->write($run, 'run_cancelled', 'Generation cancelled', null, 'Orchestrator', [], 'warning');
    }

    public function resume(CfGenerationRun $run): void
    {
        if ($run->status === 'cancelled') {
            $run->update(['status' => 'running', 'cancelled_at' => null, 'error_summary' => null]);
        } elseif (in_array($run->status, ['failed', 'generation_incomplete'], true)) {
            $failed = $run->steps()->where('status', 'failed')->orderBy('sequence')->first();
            if ($failed) {
                $failed->update(['status' => 'retrying', 'error_message' => null]);
            }
            $run->update(['status' => 'running', 'failed_at' => null, 'error_summary' => null]);
        }

        AdvanceCourseFactoryJob::dispatch($run->id);
        $this->events->write($run, 'run_resumed', 'Generation resumed', null, 'Orchestrator');
    }

    public function retryStep(CfGenerationRun $run, string $stepKey): void
    {
        $step = $run->steps()->where('step_key', $stepKey)->firstOrFail();
        $step->update([
            'status' => 'retrying',
            'error_message' => null,
            'error_code' => null,
            'progress' => 0,
        ]);
        // Reset later steps to pending so pipeline continues cleanly from this checkpoint.
        $run->steps()->where('sequence', '>', $step->sequence)->where('status', '!=', 'completed')
            ->update(['status' => 'pending', 'progress' => 0]);

        $run->update(['status' => 'running', 'failed_at' => null, 'error_summary' => null, 'current_step' => $stepKey]);
        AdvanceCourseFactoryJob::dispatch($run->id);
    }

    private function refreshProgress(CfGenerationRun $run): void
    {
        $run->refresh();
        $steps = $run->steps()->get();
        $total = max(1, $steps->count());
        $done = $steps->where('status', 'completed')->count();
        $partial = $steps->whereIn('status', ['running', 'waiting_external', 'retrying'])->sum(fn ($s) => ((int) $s->progress) / 100);
        $pct = (int) min(99, floor((($done + $partial) / $total) * 100));
        $run->update(['overall_progress' => $pct]);
    }
}
